### ISSUE TITLE
好想（）（）

### ISSUE THREAD

**Issue by RockChinQ** [wangcham/WangCham#2]
？

**Comment by RockChinQ** [comment]
要么给我一个网球，要么给我500 Q币

**Comment by wangcham** [comment]
给你个新的，[,逆天玩意儿](https://baike.baidu.com/item/%E5%82%BB%E9%80%BC/977754)，别在这[发电](http://www.taochigui.art)

**Comment by RockChinQ** [comment]
好想超你

**Comment by wangcham** [comment]
好像炒bean
